version: '3'

services:
  geoserver: # geoserver login:   user: admin    pw: geoserver
    image: terrestris/geoserver:2.15.0 # standard geoserver image from dockerhub
    container_name: geoserver
    volumes:
      - ./docker_volumes/geoserver/geoserver_data:/opt/geoserver_data/:Z # host : container
      - ./docker_volumes/geoserver/additional_libs:/opt/additional_libs/:Z
    environment:
      - EXTRA_JAVA_OPTS=-Xms1g -Xmx2g # environment variable, will be passed to dockerfile of geoserver
    depends_on:
      # postgis will be started before geoserver, but does not wait to be 'ready'
      # to do that, see here: https://docs.docker.com/compose/startup-order/
      - postgis
    networks: 
      - geoserverPhpNetwork


  # possibly important info:
  # https://stackoverflow.com/questions/34691412/docker-postgres-does-not-run-init-file-in-docker-entrypoint-initdb-d
  # https://stackoverflow.com/questions/35679995/how-to-use-a-postgresql-container-with-existing-data
  postgis: # postgres database with postgis installed
    image: mdillon/postgis:10-alpine #standard postgresql + postgis image from dockerhub
    ports:
      - 15432:5432
    container_name: postgis
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./docker_volumes/postgis/postgresql_data:/var/lib/postgresql/data:Z
    networks:
      - geoserverPhpNetwork

  php_apache:  # custom apache+php for geoserver
    image: robortgeo/apache-php-for-geoserver
    container_name: php_apache
    depends_on:
      - postgis
      - geoserver
    volumes:
      - ./docker_volumes/php/:/var/www/html/
      #- ./docker_volumes/configs/:/var/www/html/ # not available at build time!
    environment:
      - APACHE_PORT
    ports:
      - ${APACHE_PORT}:80
    networks: 
      - geoserverPhpNetwork

networks:
  geoserverPhpNetwork:
    driver: bridge